/*
 * File: app/view/MainPanel.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DataBindingDemo.view.MainPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mainpanel',

    requires: [
        'DataBindingDemo.view.MainPanelViewModel',
        'DataBindingDemo.view.PersonGrid',
        'DataBindingDemo.view.PersonView',
        'DataBindingDemo.view.PersonForm',
        'DataBindingDemo.view.PersonPanel',
        'Ext.grid.Panel',
        'Ext.view.View',
        'Ext.form.Panel'
    ],

    viewModel: {
        type: 'mainpanel'
    },
    frame: true,
    height: 600,
    itemId: 'mainPanel',
    glyph: 61675,
    title: 'ExtJS 6 MVVM Data Binding Example',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'container',
            flex: 1,
            defaults: {
                flex: 1,
                margin: 5,
                border: true
            },
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'persongrid',
                    flex: 1,
                    glyph: 61646
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    glyph: 61449,
                    title: 'DataView',
                    items: [
                        {
                            xtype: 'personview'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            flex: 1,
            defaults: {
                flex: 1,
                margin: 5,
                border: true
            },
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'personform',
                    flex: 1,
                    glyph: 61508
                },
                {
                    xtype: 'personpanel',
                    flex: 1,
                    title: 'Data Panel'
                }
            ]
        }
    ]

});