/*
 * File: app/view/PersonGrid.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DataBindingDemo.view.PersonGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.persongrid',

    requires: [
        'DataBindingDemo.view.PersonGridViewModel',
        'DataBindingDemo.view.PersonGridViewController',
        'Ext.grid.column.Column',
        'Ext.form.field.Number',
        'Ext.view.Table',
        'Ext.grid.plugin.CellEditing'
    ],

    config: {
        currentPerson: null
    },

    controller: 'persongrid',
    viewModel: {
        type: 'persongrid'
    },
    publishes: [
        'currentPerson'
    ],
    header: {
        title: 'Person Grid',
        padding: '4 9 5 9',
        items: [
            {
                text: 'New',
                xtype: 'button',
                itemId: 'add',
                glyph: 61543,
                handler: 'onGridButton'
            },
            {
                tooltip: 'Reject All',
                xtype: 'button',
                itemId: 'reject',
                handler: 'onGridButton',
                disabled: true,
                bind: {
                    disabled: '{!storeDirty}'
                },
                glyph: 61666,
                margin: '0 0 0 5'
            },
            {
                tooltip: 'Commit All',
                xtype: 'button',
                itemId: 'commit',
                handler: 'onGridButton',
                disabled: true,
                bind: {
                    disabled: '{!storeDirty}'
                },
                glyph: 61452,
                margin: '0 0 0 5'
            }
        ]
    },

    bind: {
        currentPerson: '{currentPerson}',
        title: '<b>{currentPerson.name}</b>',
        store: '{persons}'
    },
    columns: [
        {
            xtype: 'gridcolumn',
            flex: 1,
            dataIndex: 'fname',
            text: 'First Name',
            editor: {
                xtype: 'textfield'
            }
        },
        {
            xtype: 'gridcolumn',
            flex: 1,
            dataIndex: 'lname',
            text: 'Last Name',
            editor: {
                xtype: 'textfield'
            }
        },
        {
            xtype: 'gridcolumn',
            flex: 1,
            dataIndex: 'age',
            text: 'Age',
            editor: {
                xtype: 'numberfield'
            }
        }
    ],
    plugins: [
        {
            ptype: 'cellediting'
        }
    ],
    listeners: {
        select: 'onGridpanelSelect'
    }

});