/*
 * File: app/view/PersonFormViewController.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DataBindingDemo.view.PersonFormViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.personform',

    onFormButton: function(button) {
                var itemId = button.getItemId(),
                    cp = this.getView().up('#mainPanel').getViewModel().get('currentPerson');
                if (cp && cp.isModel) {
                    if (itemId === "reject") {
                        cp.reject();
                    }
                    if (itemId === "commit") {
                        cp.commit();
                        cp.reject();
                    }
                }
    }

});
