/*
 * File: app/view/PersonPanel.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DataBindingDemo.view.PersonPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.personpanel',

    requires: [
        'DataBindingDemo.view.PersonPanelViewModel',
        'Ext.XTemplate'
    ],

    viewModel: {
        type: 'personpanel'
    },
    tpl: [
        '<table><tr><td>First Name:</td><td><strong>{fname}</strong></td></tr><tr><td>Last Name:</td><td><strong>{lname}</strong></td></tr><tr><td>Age:</td><td><strong>{age}</strong></td></tr></table>'
    ],
    glyph: 61686,

    bind: {
        data: {
            bindTo: '{currentPerson}',
            deep: true
        },
        title: '<b>{currentPerson.name}</b>'
    }

});