/*
 * File: app/view/PersonForm.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DataBindingDemo.view.PersonForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.personform',

    requires: [
        'DataBindingDemo.view.PersonFormViewModel',
        'DataBindingDemo.view.PersonFormViewController',
        'Ext.form.field.Text'
    ],

    config: {
        currentPerson: null
    },

    controller: 'personform',
    viewModel: {
        type: 'personform'
    },
    bodyPadding: 10,
    header: {
        title: 'Person Form',
        padding: '4 9 5 9',
        items: [
            {
                text: 'Reject',
                xtype: 'button',
                itemId: 'reject',
                handler: 'onFormButton',
                glyph: 61666,
                disabled: true,
                bind: {
                    disabled: '{!dirty}'
                }
            },
            {
                text: 'Commit',
                xtype: 'button',
                itemId: 'commit',
                handler: 'onFormButton',
                glyph: 61452,
                margin: '0 0 0 5',
                disabled: true,
                bind: {
                    disabled: '{!dirty}'
                }
            }
        ]
    },

    bind: {
        currentPerson: '{currentPerson}',
        title: '<b>{currentPerson.name}</b>'
    },
    items: [
        {
            xtype: 'textfield',
            anchor: '100%',
            fieldLabel: 'First Name',
            bind: {
                disabled: '{!currentPerson}',
                value: '{currentPerson.fname}'
            }
        },
        {
            xtype: 'textfield',
            anchor: '100%',
            fieldLabel: 'Last Name',
            bind: {
                disabled: '{!currentPerson}',
                value: '{currentPerson.lname}'
            }
        },
        {
            xtype: 'textfield',
            anchor: '100%',
            fieldLabel: 'Age',
            bind: {
                disabled: '{!currentPerson}',
                value: '{currentPerson.age}'
            }
        }
    ]

});