/*
 * File: app/view/PersonView.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DataBindingDemo.view.PersonView', {
    extend: 'Ext.view.View',
    alias: 'widget.personview',

    requires: [
        'DataBindingDemo.view.PersonViewViewModel',
        'DataBindingDemo.view.PersonViewViewController',
        'Ext.XTemplate'
    ],

    config: {
        currentPerson: null
    },

    controller: 'personview',
    viewModel: {
        type: 'personview'
    },
    publishes: [
        'currentPerson'
    ],
    border: true,
    itemSelector: 'div.person-item',
    itemTpl: [
        '<div class="person-item"><strong>{fname} {lname}</strong> ({age})</div>'
    ],
    selectedItemCls: 'selected',

    bind: {
        currentPerson: '{currentPerson}',
        store: '{personsChained}'
    },
    listeners: {
        select: 'onDataviewSelect',
        beforecontainerclick: 'onDataviewBeforeContainerClick'
    }

});